version: "3.0"
services:
    metricbeat:
        build: .
        container_name: metricbeat
        network_mode: host
        volumes:
            - "/proc:/hostfs/proc:ro"
            - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
            - "/:/hostfs:ro"
        command: "-system.hostfs=/hostfs"